#!/usr/bin/env node
var request = require('request');
var repositoryUrl = 'https://raw.githubusercontent.com/likegun/snippets/master/';
var snippetName = process.argv[2];
if(snippetName == null) {
    console.error('请输入snippet名');
    return;
}
function pbcopy(data) {
    var proc = require('child_process').spawn('pbcopy'); 
    proc.stdin.write(data); proc.stdin.end();
}
request.get(repositoryUrl + snippetName, function(err, res, body) {
    if(err) return console.error(err);
    if(res.statusCode == 404) return console.error(`snippet不存在`);
    pbcopy(body);
    console.log('I am done, baby !');
});